name: Sync to Capstone

on:
  push:
    branches:
      - master
    paths:
      - '**/*'
  workflow_dispatch: # Memungkinkan pemicu manual dari repositori lain

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source repository
      uses: actions/checkout@v2

    - name: Set up Git for pushing changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Remove all and clone Capstone repository
      run: |
        rm -rf *
        git clone https://github.com/epialert/capstone.git ../capstone
        
    - name: Clone the other repositories
      run: |
        git clone https://github.com/epialert/cloud-computing.git ../cloud
        git clone https://github.com/epialert/mobile-development.git ../mobile

    - name: Create target directories in Capstone repo (if not exist)
      run: |
        mkdir -p ../capstone/CC
        mkdir -p ../capstone/MD

    - name: Move relevant files to capstone repo
      run: |
        echo "Moving files from the source repository..."
        mv -r ../cloud/* ../capstone/CC/
        mv -r ../mobile/* ../capstone/MD/
        
        echo "Listing files in CC folder after move:"
        ls -l ../capstone/CC/
        echo "Listing files in MD folder after move:"
        ls -l ../capstone/MD/

    - name: Check git status
      run: |
        cd ../capstone
        git status

    - name: Add and commit changes
      run: |
        cd ../capstone
        git add CC/* MD/* || echo "No files to add"
        git commit -m "Sync changes from $GITHUB_REPOSITORY" || echo "No changes to commit"

    - name: Commit and push changes to Capstone
      run: |
        cd ../capstone
        git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/epialert/capstone.git master
