name: Sync to Capstone

on:
  push:
    branches:
      - master
    paths:
      - '**/*'
  workflow_dispatch: # Memungkinkan pemicu manual dari repositori lain

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source repository
      uses: actions/checkout@v2

    - name: Set up Git for pushing changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone or pull Capstone repository
      run: |
        if [ ! -d "../capstone" ]; then
          git clone https://github.com/epialert/capstone.git ../capstone
        else
          cd ../capstone
          git pull origin master
        fi

    - name: Clone the other repositories
      run: |
        git clone https://github.com/epialert/cloud-computing.git ../cloud-computing
        git clone https://github.com/epialert/mobile-development.git ../mobile-development

    - name: Create target directories in Capstone repo (if not exist)
      run: |
        mkdir -p ../capstone/CC
        mkdir -p ../capstone/MD

    - name: Copy relevant files to capstone repo
      run: |
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        if [ "$GITHUB_REPOSITORY" == "epialert/cloud-computing" ]; then
          cp -r ../cloud-computing/* ../capstone/CC/
        elif [ "$GITHUB_REPOSITORY" == "epialert/mobile-development" ]; then
          cp -r ../mobile-development/* ../capstone/MD/
        else
          echo "This workflow is not triggered from the expected repositories."
        fi
        
        echo "Listing files in CC folder after copy:"
        ls -l ../capstone/CC/
        echo "Listing files in MD folder after copy:"
        ls -l ../capstone/MD/

    - name: Check git status
      run: |
        cd ../capstone
        git status

    - name: Add and commit changes
      run: |
        cd ../capstone
        git add CC/* MD/* || echo "No files to add"
        git commit -m "Sync changes from $GITHUB_REPOSITORY" || echo "No changes to commit"

    - name: Commit and push changes to Capstone
      run: |
        cd ../capstone
        git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/epialert/capstone.git master
