name: Sync to Capstone

on:
  push:
    branches:
      - master  # Ganti dengan branch utama dari repositori kamu
    paths:
      - '**/*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the source repository
      uses: actions/checkout@v2

    - name: Set up Git for pushing changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add Capstone repository as remote
      run: |
        git remote add capstone https://github.com/epialert/capstone.git

    - name: Create target directories in Capstone repo (if not exist)
      run: |
        mkdir -p ../capstone/CC
        mkdir -p ../capstone/MD
        mkdir -p ../capstone/ML

    - name: Copy relevant files to capstone repo
      run: |
        if [ "$GITHUB_REPOSITORY" == "epialert/cloud-computing" ]; then
          cp -r * ../capstone/CC/
        elif [ "$GITHUB_REPOSITORY" == "epialert/mobile-development" ]; then
          cp -r * ../capstone/MD/
        elif [ "$GITHUB_REPOSITORY" == "epialert/machine-learning" ]; then
          cp -r * ../capstone/ML/
        fi
        # Verify that files were copied successfully
        echo "Listing files in the target directory:"
        ls -l ../capstone/CC/
        ls -l ../capstone/MD/
        ls -l ../capstone/ML/

    - name: Check git status
      run: |
        cd ../capstone
        git status

    - name: Add and commit changes
      run: |
        cd ../capstone
        # Debugging: Check if files exist
        echo "Checking files in CC folder"
        ls -l CC/
        echo "Checking files in MD folder"
        ls -l MD/
        echo "Checking files in ML folder"
        ls -l ML/

        # Add files explicitly
        git add ../capstone/CC/* ../capstone/MD/* ../capstone/ML/* || echo "No files to add"
        git status  # Ensure changes are detected
        git commit -m "Sync changes from $GITHUB_REPOSITORY" || echo "No changes to commit"

    - name: Commit and push changes to Capstone
      run: |
        cd ../capstone
        git push https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com/epialert/capstone.git master
