name: Sync to folder

on:
  repository_dispatch:
    types: [sync-capstone-repo] # Event type yang dikirimkan dari repositori lain

jobs:
  sync:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2

      - name: Set up Git for pushing changes
        run: |
          git config --global user.name "Affidev"
          git config --global user.email "eabdalmufid@gmail.com"

      - name: Remove Folder directory if it exists
        run: |
          if [ -d "./folder" ]; then
            rm -rf ./folder
            echo "folder directory removed."
          fi

      - name: Clone Folder repository
        run: |
          mkdir -p folder
          git clone https://github.com/epialert/folder.git folder
          ls -l folder  # Untuk memverifikasi isi direktori

      - name: Clone the other repositories
        run: |
          git clone https://github.com/epialert/cloud-computing.git cloud
          git clone https://github.com/epialert/mobile-development.git mobile
          git clone https://github.com/epialert/machine-learning.git machine

      - name: Create target directories in Folder repo (if not exist)
        run: |
          mkdir -p folder/CC
          mkdir -p folder/MD
          mkdir -p folder/ML

      - name: Move relevant files to Folder repo
        run: |
          echo "Moving files from the source repository..."
          rsync -av --remove-source-files cloud/ folder/CC/
          rsync -av --remove-source-files mobile/ folder/MD/
          rsync -av --remove-source-files machine/ folder/ML/

          echo "Listing files in CC folder after move:"
          ls -l folder/CC/
          echo "Listing files in MD folder after move:"
          ls -l folder/MD/
          echo "Listing files in ML folder after move:"
          ls -l folder/ML/

      - name: Check git status
        run: |
          cd folder
          git status

      - name: Add and commit changes
        run: |
          cd folder
          git add CC/* MD/* ML/* || echo "No files to add"
          git commit -m "Sync changes from $GITHUB_REPOSITORY" || echo "No changes to commit"

      - name: Commit and push changes to folder
        run: |
          cd folder
          git push https://github-actions[bot]:${{ secrets.folder_TOKEN }}@github.com/epialert/folder.git master
